### ISSUE TITLE
trying out your repo, but there appears to be a worker process

### ISSUE THREAD

**Issue by minoseah629** [alexellis/aspnet-voteservice#1]
hello, 
i am going through your repo, but when i did a docker-compose up on the docker-compose.test.yml, there is a reference called worker, but the worker folder does not exist.  

is there supposed to be a worker service or not?

https://github.com/alexellis/aspnet-voteservice/blob/946305e3c8cb192228ff01a43181f0b82beb8e5f/result/docker-compose.test.yml#L10

**Comment by minoseah629** [comment]
i forked your repo and made some adjustments to make compose work.
also on docker version 2.1.0.6 as well. 

https://github.com/minoseah629/aspnet-voteservice

```
C:\Repos\aspnet-voteservice [o/master ≡]> docker-compose -f "result\docker-compose.test.yml" up -d --build
Creating network "result_back-tier" with the default driver
Creating network "result_front-tier" with the default driver
Building result
Step 1/12 : FROM stefanscherer/node-windows:4.6
 ---> ed15eee5afc8
Step 2/12 : MAINTAINER alexellis2@gmail.com
 ---> Using cache
 ---> 758a20bac06d
Step 3/12 : WORKDIR /app
 ---> Using cache
 ---> 2dcd486054d6
Step 4/12 : RUN npm install -g nodemon     
 ---> Using cache
 ---> 723edd26d640
Step 5/12 : ADD package.json /app/package.json
 ---> Using cache
 ---> 2960c7dea522
Step 6/12 : RUN npm config set registry http://registry.npmjs.org
 ---> Using cache
 ---> 82f0364fc2cb
Step 7/12 : RUN npm install
 ---> Using cache
 ---> d85f30cd8769
Step 8/12 : RUN mv /app/node_modules /node_modules
 ---> Using cache
 ---> 344b3eae7d4c
Step 9/12 : ADD . /app
 ---> Using cache
 ---> dfed592c76bb
Step 10/12 : ENV PORT 4000
 ---> Using cache
 ---> d88fac054a36
Step 11/12 : EXPOSE 4000
 ---> Using cache
 ---> ef17458b94b6
Step 12/12 : CMD ["node", "server.js"]
 ---> Using cache
 ---> dad9791a9615
Successfully built dad9791a9615
Successfully tagged result_result:latest
Building vote
Step 1/12 : FROM mcr.microsoft.com/windows/servercore:ltsc2019
 ---> 49e459dc7a6b
Step 2/12 : MAINTAINER alexellis2@gmail.com
 ---> Using cache
 ---> 062ab161772d
Step 3/12 : SHELL ["powershell"]
 ---> Using cache
 ---> 715302c97301
Step 4/12 : RUN $ErrorActionPreference = 'Stop';     wget https://www.python.org/ftp/python/2.7.12/python-2.7.12.msi -OutFile python-2.7.12.msi ;     Start-Process python-2.7.12.msi -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait ;     Remove-Item python-2.7.12.msi -Force
 ---> Using cache
 ---> a782a78abbae
Step 5/12 : WORKDIR /app
 ---> Using cache
 ---> db9a18b0b48c
Step 6/12 : RUN setx PATH '%PATH%;C:\\Python27\\'
 ---> Using cache
 ---> d422b1fb0868
Step 7/12 : ADD requirements.txt /app/requirements.txt
 ---> Using cache
 ---> 9d2d9b085418
Step 8/12 : ENV PYTHONIOENCODING=UTF-8
 ---> Using cache
 ---> 0d118d027142
Step 9/12 : RUN C:\\Python27\\python.exe -m pip install --upgrade pip ;     C:\\Python27\\python.exe -m pip install -r requirements.txt
 ---> Using cache
 ---> 8cb3455b84e5
Step 10/12 : ADD . /app
 ---> Using cache
 ---> 04bfeca0567a
Step 11/12 : EXPOSE 80
 ---> Using cache
 ---> 3b1729f4fc19
Step 12/12 : CMD ["C:\\Python27\\python.exe", ".\\app.py"]
 ---> Using cache
 ---> c71fd10db4e3
Successfully built c71fd10db4e3
Successfully tagged result_vote:latest
Building sut
Step 1/5 : FROM node
 ---> 1a77bcb355eb
Step 2/5 : RUN npm install -g phantomjs
 ---> Running in f28186c3b7fe
npm WARN deprecated phantomjs@2.1.7: Package renamed to phantomjs-prebuilt. Please update 'phantomjs' package references to 'phantomjs-prebuilt'
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated hawk@3.1.3: This module moved to @hapi/hawk. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated tough-cookie@2.2.2: ReDoS vulnerability parsing Set-Cookie https://nodesecurity.io/advisories/130
npm WARN deprecated hoek@2.16.3: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated cryptiles@2.0.5: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug 
fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
npm WARN deprecated sntp@1.0.9: This module moved to @hapi/sntp. Please make sure to switch over as this distribution is no longer supported and may contain bugs and critical security issues.
npm WARN deprecated boom@2.10.1: This version has been deprecated in accordance with the hapi support policy (hapi.im/support). Please upgrade to the latest version to get the best features, bug fixes, and security patches. If you are unable to upgrade at this time, paid support is available for older versions (hapi.im/commercial).
/usr/local/bin/phantomjs -> /usr/local/lib/node_modules/phantomjs/bin/phantomjs

> phantomjs@2.1.7 install /usr/local/lib/node_modules/phantomjs
> node install.js

Considering PhantomJS found at /usr/local/bin/phantomjs
Looks like an `npm install -g`
Error checking path, continuing Error: Cannot find module '/usr/local/lib/node_modules/phantomjs/lib/location'
Require stack:
- /usr/local/lib/node_modules/phantomjs/install.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:892:15)
    at Function.Module._load (internal/modules/cjs/loader.js:785:27)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getLocationInLibModuleIfMatching (/usr/local/lib/node_modules/phantomjs/install.js:332:19)
    at Promise._successFn (/usr/local/lib/node_modules/phantomjs/install.js:389:28)
    at nextTickCallback (/usr/local/lib/node_modules/phantomjs/node_modules/kew/kew.js:47:28)
    at processTicksAndRejections (internal/process/task_queues.js:75:11) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/local/lib/node_modules/phantomjs/install.js' ]
}
/usr/local/lib/node_modules/phantomjs/phantomjs is not writable: EACCES: permission denied, mkdir '/usr/local/lib/node_modules/phantomjs/phantomjs'
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1//phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Removing /usr/local/lib/node_modules/phantomjs/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1574186820240/phantomjs-2.1.1-linux-x86_64 -> /usr/local/lib/node_modules/phantomjs/lib/phantom
Phantom installation failed [Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1574186820240/phantomjs-2.1.1-linux-x86_64' -> '/usr/local/lib/node_modules/phantomjs/lib/phantom'] {
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1574186820240/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/local/lib/node_modules/phantomjs/lib/phantom'
} Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1574186820240/phantomjs-2.1.1-linux-x86_64' -> '/usr/local/lib/node_modules/phantomjs/lib/phantom'
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! phantomjs@2.1.7 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@2.1.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-11-19T18_07_04_040Z-debug.log
ERROR: Service 'sut' failed to build: The command '/bin/sh -c npm install -g phantomjs' returned a non-zero code: 1
```
